name       : python-d2to1
version    : 0.2.12
release    : 6
source     :
    - https://pypi.python.org/packages/dc/bd/eac45e4e77d76f6c0ae539819c40f1babb891d7855129663e37957a7c2df/d2to1-0.2.12.post1.tar.gz : 49ef2d16862b3efdc81fc5c32eac373b984945cde5fc02bb01a0a11ff03dd825
license    : BSD-3-Clause
component  : programming.python
summary    : Allows using distutils2-like setup.cfg files for a package's metadata with a distribute/setuptools setup.py
description: |
    d2to1 (the 'd' is for 'distutils') allows using distutils2-like setup.cfg files for a package's metadata with a distribute/setuptools setup.py script. It works by providing a distutils2-formatted setup.cfg file containing all of a package's metadata, and a very minimal setup.py which will slurp its arguments from the setup.cfg.
setup      : |
    %python3_setup
install    : |
    %python3_install
